### ISSUE TITLE
How to train Market1501

### ISSUE THREAD

**Issue by lucy3589** [xbq1994/HAA#12]
When I trained the two data sets you provided, no errors were reported and the results were correct.  However, when training the Open-Market1501 dataset, an error is reported.
`
----------------------------------------------------outputs[0] torch.Size([12, 688])
----------------------------------------------------outputs[1] torch.Size([12, 1536])
----------------------------------------------------outputs[2] torch.Size([12])
----------------------------------m,n 12 12
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [7,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [8,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [9,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [10,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [0,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../../fastreid/modeling/losses/metric_loss.py:33: UserWarning: This overload of addmm_ is deprecated:
        addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
        addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  dist.addmm_(1, -2, x, y.t())
ERROR [07/07 20:33:30 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "../../fastreid/engine/train_loop.py", line 121, in train
    self.run_step()
  File "train_net.py", line 51, in run_step
    loss_dict = self.model.module.losses(outputs,self.iter)
  File "../../fastreid/modeling/meta_arch/HAA_BASELINE.py", line 167, in losses
    loss_dict.update(reid_losses(self._cfg, outputs[0][0], outputs[1][0], outputs[2],0.2, 0.2,'gf_'))
  File "../../projects/Black_reid/build_losses.py", line 11, in reid_losses
    loss = getattr(Loss, cfg.MODEL.LOSSES.NAME[1])(cfg)(pred_class_logits, global_features, gt_classes)
  File "../../fastreid/modeling/losses/metric_loss.py", line 149, in __call__
    dist_mat = euclidean_dist(global_features, global_features)
  File "../../fastreid/modeling/losses/metric_loss.py", line 33, in euclidean_dist
    dist.addmm_(1, -2, x, y.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f91a2cbd8b2 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f91a2f0f952 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f91a2ca8b7d in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0xaac8b9 (0x7f91e0e378b9 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x27ca653 (0x7f91e2b55653 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x2bff672 (0x7f91e2f8a672 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f91e2f8a71f in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x485319 (0x7f91f1527319 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: c10::TensorImpl::release_resources() + 0x20 (0x7f91a2ca8b50 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x5ff5ba (0x7f91f16a15ba in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x5ff666 (0x7f91f16a1666 in /opt/miniconda3/envs/torch1.7/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #33: __libc_start_main + 0xe7 (0x7f91f4151bf7 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
`

**Comment by mumuner** [comment]
Hi, have you fixed this problem？I want to try on my own dataset, Can you tell me how to train on other dataset?
