### ISSUE TITLE
网络如何约束头肩的位置

### ISSUE THREAD

**Issue by Chaucergit** [xbq1994/HAA#2]
首先不得不说**Black ReID**是一个非常有价值的工作，对于实际的工程实践也是非常有用的！！！<br>
这里有一个疑惑，看模型是通过STN中的**Translation**的特性来局部定位在头肩的位置，但是如何确定或者约束才能使得模型提取的特征是头肩呢？看源码里面的loss都是针对【Local or Global Feature】分类**CrossEntropy Loss**或者度量**Triplet Loss**，还有一个**IOU Loss**但是源码里面没见使用这个来进行约束，暂时没想明白网络怎么注意到头肩位置的？<br>
非常想了解一下，谢谢啦！！<br>

**Comment by xbq1994** [comment]
感谢你的关注~黑衣人数据库中我们先标注了头肩的位置，然后用IOU Loss来训练STN。下载的STN模型就是通过这种方法在黑衣人数据库上预训练好了的。在后面的训练过程中STN都是冻结的，所以代码里面没有显示IOU Loss。

**Comment by Chaucergit** [comment]
嗯嗯，非常感谢，理解了，只看了你们的论文和源码，还没有下载你们的数据集和权重。
