### ISSUE TITLE
头肩提取

### ISSUE THREAD

**Issue by sky186** [xbq1994/HAA#5]
@xbq1994      
   #HSA branch
        stn = self.stn(images)  

        #HSA_branch  ,原图先定位到肩膀数据，头肩数据
        self.stn = SpatialTransformBlock(1,24,512)  #HLL 利用仿射变换来回归出头肩的bbox
        model_dict =self.stn.state_dict() 
        pretrained_dict = torch.load(self._cfg.DATASETS.STN_ROOT)
        pretrained_dict =  {k[4:]: v for k, v in pretrained_dict.items() if k.startswith('stn')} 
        self.stn.load_state_dict(pretrained_dict)  
        for param in self.stn.parameters():
            param.requires_grad = False
1、我想问请教下这个问题，头肩图像的 返回，stn 这个模型参数是固定的，不更新，只是作为一种数据处理，得到 HSA的模型分支的输入？

2、stn 模型得到的效果是很好吗？

3、stn 的模型参数是你们自己根据黑衣服的数据集训练的吗？

**Comment by TragedyN** [comment]
请问您对前两个问题有答案了吗

**Comment by xbq1994** [comment]
是的，STN会先对原图进行crop得到头肩区域作为HSA模型的输入。HSA模型是我们在黑衣人数据集上预训练好的，效果不错，能够满足头肩区域定位的精度要求。

**Comment by TragedyN** [comment]
@xbq1994 你好，我也想请教几个关于头肩提取的问题
1.STN是否是专注于图像中上半区域（头肩基本在上半区域），要是输入的图像是一个躺着的人，效果会如何？
2.更精准的头肩区域提取是否有助于效果的提升？
3.是否尝试过只用人头区域？效果如何？

**Comment by xbq1994** [comment]
1：STN是专注于头肩，而并非广泛意义的上半身。由于我们的数据集里面没有躺着的人，所以现在预训练的STN肯定没法定位躺着的人的头肩区域。但如果专门用这类照片进行训练，应该也是可以得到有效的STN模型。
2：我们没有试过更精准的头肩定位模型。因为我们既要考虑模型精度也要考虑模型参数量，更精准的订位模块意味着模型更大。而且从可视化结果来看STN定位的头肩区域精度已经足够高了，再提升头肩定位精度应该意义不大。当然这是我的猜想，并没有做过相关实验。
3：我们尝试过只利用人头，但是效果不如头肩区域好。原因应该是头肩包含的local information更多所以效果更好。

**Comment by TragedyN** [comment]
> 1：STN是专注于头肩，而并非广泛意义的上半身。由于我们的数据集里面没有躺着的人，所以现在预训练的STN肯定没法定位躺着的人的头肩区域。但如果专门用这类照片进行训练，应该也是可以得到有效的STN模型。
> 2：我们没有试过更精准的头肩定位模型。因为我们既要考虑模型精度也要考虑模型参数量，更精准的订位模块意味着模型更大。而且从可视化结果来看STN定位的头肩区域精度已经足够高了，再提升头肩定位精度应该意义不大。当然这是我的猜想，并没有做过相关实验。
> 3：我们尝试过只利用人头，但是效果不如头肩区域好。原因应该是头肩包含的local information更多所以效果更好。

感谢回复
