### ISSUE TITLE
How to train on the other datasets?

### ISSUE THREAD

**Issue by gmt710** [xbq1994/HAA#8]
Greatly thanks for your job. This is a Re-ID issue that I am very concerned about.
I've reproduced the result on the black-reid datasets.I found the result is good in the paper.
How can I train on the other datasets ? I've tried but find that we need the flag "black_id".Do I need to make a corresponding dataset?
Would you mind giving some suggestions?

**Comment by xbq1994** [comment]
Thank you for your concern about our work.  If you want to train this model on your own dataset, firstly, you need the bbox of the head-shoulder region for training the STN module. Then, you need the "black_id" label for the pedestrians: giving label '1' to the people in black clothes.
